USE SAKILA;

create or replace view view1
as
SELECT 
  CUSTOMERNAME AS CLIENTE, 
  AMOUNT AS VALOR_PAGO, 
  SUM(PRICEEACH * QUANTITYORDERED) AS TOTAL_NOTA, 
  CHECKNUMBER AS NUMERO_PAGAMENTO,
  CASE 
    WHEN SUM(PRICEEACH * QUANTITYORDERED) <> AMOUNT THEN CONCAT(' Conversa com o representante: ', FIRSTNAME, ' ', LASTNAME)
    ELSE 'Tudo certo'
  END AS ANALISE    
FROM 
  ORDERDETAILS
    INNER JOIN ORDERS USING (ORDERNUMBER)
    INNER JOIN CUSTOMERS USING (CUSTOMERNUMBER)
    INNER JOIN PAYMENTS USING (CUSTOMERNUMBER)
    INNER JOIN EMPLOYEES ON SALESREPEMPLOYEENUMBER = EMPLOYEENUMBER
WHERE 
    YEAR(PAYMENTDATE) = YEAR(ORDERDATE)
AND MONTH(PAYMENTDATE) = MONTH(ORDERDATE)
GROUP BY
  CLIENTE, AMOUNT, NUMERO_PAGAMENTO
ORDER BY 
  NUMERO_PAGAMENTO
LIMIT 20;

create or replace view view2
as
SELECT 
  SUM(QUANTITYORDERED), 
  PRODUCTNAME,
  'PRODUTOS' AS OBSERVACAO
FROM
  ORDERS
    INNER JOIN ORDERDETAILS USING (ORDERNUMBER)
    INNER JOIN PRODUCTS USING (PRODUCTCODE)
WHERE
  YEAR(ORDERDATE) = 2004
GROUP BY
  PRODUCTNAME
HAVING 
  SUM(QUANTITYORDERED) BETWEEN 400 AND 800;
 
 create or replace view view3
as
SELECT 
  SUM(AMOUNT), 
  CUSTOMERNAME, 
  'CLIENTE' AS OBSERVACAO
FROM 
  PAYMENTS 
    INNER JOIN CUSTOMERS USING (CUSTOMERNUMBER)
    INNER JOIN EMPLOYEES ON SALESREPEMPLOYEENUMBER = EMPLOYEENUMBER
    INNER JOIN OFFICES USING (OFFICECODE)
WHERE 
   MONTH(PAYMENTDATE) IN (10,11,12)
AND YEAR(PAYMENTDATE) = 2004
AND OFFICES.CITY IN ('London', 'San Francisco')
GROUP BY
   CUSTOMERNAME
HAVING 
  SUM(AMOUNT) > 50000;

create or replace view view4
as
SELECT 
  SUM(AMOUNT), 
  CONCAT(FIRSTNAME,' ', LASTNAME), 
  'VENDEDORES' AS OBSERVACAO
FROM 
  PAYMENTS 
    INNER JOIN CUSTOMERS USING (CUSTOMERNUMBER)
    INNER JOIN EMPLOYEES ON SALESREPEMPLOYEENUMBER = EMPLOYEENUMBER
WHERE 
  YEAR(PAYMENTDATE) = 2005
HAVING 
  SUM(AMOUNT) > 200000;
  
  
create or replace view view5
as

SELECT 
   NAME AS CATEGORIA, 
   STORE_ID AS LOJA, 
   COUNT(INVENTORY_ID) AS QTDE
FROM 
  CATEGORY
    INNER JOIN FILM_CATEGORY USING (CATEGORY_ID)
    INNER JOIN FILM USING (FILM_ID)
    INNER JOIN INVENTORY USING (FILM_ID)
WHERE 
   NAME IN ('Comedy', 'Drama')
GROUP BY
  CATEGORIA, LOJA;
  
create or replace view todas_views
as
select * from view1
union
select * from view2
union
select * from view3
union
select * from view4
union
select * from view5;

select * from todas_views;


-- Prova b
USE SAKILA;

create or replace view view_b1
as
SELECT 
   CONCAT(FIRST_NAME, ' ', LAST_NAME) AS NOME_COMPLETO, 
   SUM(AMOUNT) AS VALOR_PAGO, 
   IFNULL( RENTAL_DURATION - CAST(DATEDIFF(RETURN_DATE, RENTAL_DATE) AS DECIMAL), 999) AS ANALISE_DIA, 
   CASE
      WHEN SUM(AMOUNT) = RENTAL_RATE THEN CONCAT('Valor Correto')
      ELSE 'Investigar'
   END AS ANALISE
FROM 
  CUSTOMER
    INNER JOIN PAYMENT USING (CUSTOMER_ID)
    INNER JOIN RENTAL USING (RENTAL_ID)
    INNER JOIN INVENTORY USING (INVENTORY_ID)
    INNER JOIN FILM USING (FILM_ID)
WHERE 
  YEAR(PAYMENT_DATE) = 2005
AND MONTH(PAYMENT_DATE) = 8
GROUP BY
  NOME_COMPLETO, ANALISE_DIA
ORDER BY
  ANALISE_DIA ASC
LIMIT 10;


create or replace view view_b2
as
SELECT 
   TITLE AS TITULO, 
   STORE_ID AS LOJA, 
   NAME AS CATEGORIA, 
   COUNT(INVENTORY_ID) AS QTDE
FROM 
   CATEGORY 
     INNER JOIN FILM_CATEGORY USING (CATEGORY_ID)
     INNER JOIN FILM USING (FILM_ID)
     INNER JOIN INVENTORY USING (FILM_ID)
     LEFT JOIN RENTAL USING (INVENTORY_ID)
WHERE 
  RENTAL_ID IS NULL
GROUP BY
  TITULO, LOJA, CATEGORIA;


create or replace view view_b3
as
SELECT 
   COUNT(CUSTOMER_ID), 
   'Total de clientes inativos' AS OBSERVACAO
FROM 
  CUSTOMER 
WHERE 
  ACTIVE =0;

create or replace view view_b4
as
SELECT 
  COUNT(FILM_ID), 
  'Total de filmes faltantes no estoque'
FROM 
  FILM 
    LEFT JOIN INVENTORY USING (FILM_ID)
WHERE 
  INVENTORY_ID IS NULL;

create or replace view view_b5
as
SELECT 
  COUNT(RENTAL_ID),
  'Total de aluguéis sem data de retorno'
FROM 
   RENTAL
WHERE
   RETURN_DATE IS NULL;
   
create or replace view todas_views_b
as
select * from view_b1
union
select * from view_b2
union
select * from view_b3
union
select * from view_b4
union
select * from view_b5;

select * from todas_views2;
