select * FROM ANALISE_CLIENTE;

create view CLIENTE(NOMECLIENTE, CIDADE, LIMITE_CREDITO, ENDERECO)

AS
	select CUSTOMERNAME, CITY, CREDITLIMIT, ADDRESSLINE1 from CUSTOMERS;
    
DROP VIEW CLIENTE;

select * FROM CLIENTE;