/*
INTRODUÇÃO A SORED PROCEDURES
*/

-- MODIFICANDO OS DELIMITADORES
DELIMITER %
CREATE PROCEDURE SP_CLIENTE(OUT NOME VARCHAR(50))
BEGIN

SELECT CUSTOMERNAME INTO NOME FROM CUSTOMERS WHERE CUSTOMERNUMBER = 103;

END%
DELIMITER ;

DROP PROCEDURE SP_CLIENTE;
CALL SP_CLIENTE(@VALOR);
SELECT @VALOR;

