USE SAKILA;

SELECT
	FILM_ID
FROM
	FILM LEFT JOIN INVENTORY USING (FILM_ID)
WHERE
	INVENTORY_ID IS NULL;
    
DESCRIBE INVENTORY;

DELIMITER $
CREATE PROCEDURE INSERIR_FILME_ESTOQUE_LOJA(IN CODIGOLOJA INT, IN NUMEROMATRICULA INT)
BEGIN
	DECLARE CODIGO_FILME INT;
    DECLARE DONE BOOL;
    
    DECLARE CURSOR_FILME_FALTANTES CURSOR FOR
		SELECT
			FILM_ID
		FROM FILM LEFT JOIN INVENTORY USING(FILM_ID);
	
    DECLARE CONTINUE HANDLER FOR 
		NOT FOUND SET DONE = TRUE;
        
	OPEN CURSOR_FILME_FALTANTES;
    
    LIST_FILMES: LOOP
		FETCH CURSOR_FILME_FALTANTES INTO CODIGO_FILME;
        IF DONE = TRUE THEN
			LEAVE LIST_FILMES;
		END IF;
        CONTADOR = 0;
        REPEAT
        INSERT INTO INVENTORY(INVENTORY_ID, FILM_ID, STORE_ID)
			VALUES(DEFAULT, CODIGO_FILME, CODIGOLOJA);
            SET CONTADOR += CONTADOR;
		UNTIL CONTADOR > 22301461
        END REPEAT;
	END LOOP;
    
    CLOSE CURSOR_FILME_FALTANTES;
    
    SELECT "INSERT REALIZADO COM SUCESSO!"



