USE CLASSICMODELS;

/* ATIVIDADE PREPARATORIO - PROVA FINAL A */

-- QUESTÃO 1 
CREATE OR REPLACE VIEW QUESTAO_1
AS
SELECT 
   PRODUCTNAME AS PRODUTO, 
   PRODUCTCODE AS CODIGOPRODUTO,
   COUNT(QUANTITYORDERED) AS QUANTIDADE_COMPRADA, 
   SUM(PRICEEACH * QUANTITYORDERED) AS TOTAL_PAGO, 
   CUSTOMERNUMBER AS CODIGOCLIENTE
FROM 
   PRODUCTS 
     INNER JOIN ORDERDETAILS USING (PRODUCTCODE)
     INNER JOIN ORDERS USING (ORDERNUMBER)
WHERE 
    YEAR(ORDERDATE) = 2003
AND MONTH(ORDERDATE) IN (1,5,10)
GROUP BY
  PRODUTO;
  
  
-- QUESTÇAO 2
WITH CTE_CLIENTE(CODIGOCLIENTE, EMPLOYEENUMBER)
AS (
  SELECT 
    CUSTOMERNUMBER, SALESREPEMPLOYEENUMBER
  FROM 
    CUSTOMERS), 
    CTE_EMPPREGADO(EMPLOYEENUMBER, OFFICECODE)
AS (
   SELECT 
      EMPLOYEENUMBER, OFFICECODE
   FROM 
     EMPLOYEES ),     
   CTE_ESCRITORIO(OFFICECODE, CIDADE)
AS (
   SELECT 
     OFFICECODE, CITY
   FROM
     OFFICES )
     
  SELECT 
     PRODUTO, 
     QUANTIDADE_COMPRADA, 
     TOTAL_PAGO
  FROM 
    QUESTAO_1 
       INNER JOIN CTE_CLIENTE USING (CODIGOCLIENTE)
       INNER JOIN CTE_EMPPREGADO USING (EMPLOYEENUMBER)
       INNER JOIN CTE_ESCRITORIO USING (OFFICECODE)
   WHERE 
     CIDADE IN ('TOKYO', 'LONDON');
     
-- QUESTÃO 3
SELECT 
   PRODUCTNAME AS PRODUTO, 
   SUM(QUANTITYORDERED) AS QUANTIDADE_COMPRADA, 
   SUM(PRICEEACH * QUANTITYORDERED) AS TOTAL_PAGO, 
   quantityInStock AS ESTOQUE
FROM 
   PRODUCTS 
     INNER JOIN ORDERDETAILS USING (PRODUCTCODE)
     INNER JOIN ORDERS USING (ORDERNUMBER)
WHERE 
    YEAR(ORDERDATE) = 2003
GROUP BY
  PRODUTO;
  
CREATE TABLE ANALISE_ESTOQE 
( 
  CodigoProduto VARCHAR(10), 
  OBSERVACAO VARCHAR(200)
) ENGINE = INNODB;


DELIMITER $
CREATE PROCEDURE QUESTAO_3_3(IN PARAM_ANO INT)
BEGIN
   DECLARE TOTAL_REGISTROS INT DEFAULT 0;
   DECLARE CONTADOR INT DEFAULT 0;
   DECLARE VAR_PRODUTO VARCHAR(10);
   DECLARE VAR_DESCRICAO VARCHAR(200);
   
   
   SELECT COUNT(*) INTO TOTAL_REGISTROS 
   FROM 
   PRODUCTS 
     INNER JOIN ORDERDETAILS USING (PRODUCTCODE)
     INNER JOIN ORDERS USING (ORDERNUMBER)
   WHERE 
    YEAR(ORDERDATE) = PARAM_ANO
   GROUP BY
     PRODUCTCODE;
   
   REPEAT 
    INSERT INTO ANALISE_ESTOQE 
    SELECT 
       PRODUCTNAME AS PRODUTO, 
       CASE 
         WHEN FORMAT(SUM(QUANTITYORDERED)/(SUM(QUANTITYORDERED) + quantityInStock) * 100, 2) > 70 
           THEN 'Atenção produto está precisando ser reposto. Por favor, solicite ao fornecedor!'
         WHEN FORMAT(SUM(QUANTITYORDERED)/(SUM(QUANTITYORDERED) + quantityInStock) * 100, 2) between 60 AND 70
           THEN 'O produto precisa ser reposto impediatamente! Ligue agora para o fornecedor!'
		 ELSE 
            'Produto controlado'
	   END AS RESULTADO        
    FROM 
      PRODUCTS 
        INNER JOIN ORDERDETAILS USING (PRODUCTCODE)
        INNER JOIN ORDERS USING (ORDERNUMBER)
    WHERE 
       YEAR(ORDERDATE) = 2003
    GROUP BY
      PRODUTO
	LIMIT 1 OFFSET CONTADOR;
    
    SET CONTADOR = CONTADOR + 1;
   
   
   UNTIL CONTADOR = Total_registros
   END REPEAT;

END$
DELIMITER ;


USE SAKILA;
-- QUESTÃO 4
DELIMITER $
CREATE PROCEDURE QUESTAO_4 (IN PARAM_CATEGORIA VARCHAR(20))
BEGIN
   
   SELECT 
      TITLE, 
      COUNT(ATOR_ID)
   FROM 
     CATEGORY
       INNER JOIN FILM_CATEGORY USING (CATEGORY_ID)
       INNER JOIN FILM USING (FILM_ID)
       INNER JOIN FILM_ACTOR USING (FILM_ID)
   WHERE 
     CATEGORY.NOME = PARAM_CATEGORIA
   GROUP BY
     TITLE;
END$
DELIMITER ;

-- QUESTÃO 5
USE WORLD;

CREATE TABLE QUESTAO_5
SELECT 
  LANGUAGE, 
  FORMAT(SUM(PERCENTAGE * POPULATION)/100, 2) FALANTES
FROM 
  COUNTRY 
    INNER JOIN COUNTRYLANGUAGE ON COUNTRYCODE = CODE 
WHERE 
    NAME = 'BRAZIL'
AND LANGUAGE IN ('GERMAN', 'ITALIAN', 'JAPANESE')
GROUP BY
  LANGUAGE;