-- PROVA A LETRA B
WITH CTE_PRODUTO (CODIGOPRODUTO, NOMEPRODUTO) 
AS (
 SELECT 
   PRODUCTCODE, 
   PRODUCTNAME
 FROM PRODUCTS
), 
  CTE_ITEMPEDIDO (CODIGOPRODUTO, QUANTIDADE, NUMERONOTA)
AS (
  SELECT 
	PRODUCTCODE, 
    QUANTITYORDERED, 
    ORDERNUMBER
  FROM 
    ORDERDETAILS
), 
  CTE_PEDIDO (NUMERONOTA, DATAPEDIDO)
AS (
  SELECT 
    ORDERNUMBER, 
    ORDERDATE
  FROM 
    ORDERS), 
  CTE_CLIENTE (CODIGOCLIENTE, NOMECLIENTE, CODIGOVENDEDOR)
AS (
   SELECT
	CUSTOMERNUMBER, 
    CUSTOMERNAME, 
    SALESREPEMPLOYEENUMBER
   FROM 
	 CUSTOMERS
), 
  CTE_PAGAMENTO (CODIGOCLIENTE, VALOR, DATAPAGAMENTO)
AS (
   SELECT 
     CUSTOMERNUMBER, 
     AMOUNT, 
     PAYMENTDATE
   FROM 
     PAYMENTS
 ), 
  CTE_VENDEDOR (CODIGOVENDEDOR, CODIGOESCRITORIO, NOMEVENDEDOR)
  AS (
    SELECT 
      EMPLOYEENUMBER, 
      OFFICECODE, 
      CONCAT(FIRSTNAME, ' ', LASTNAME)
	FROM 
      EMPLOYEES
 ), 
  CTE_ESCRITORIO (CODIGOESCRITORIO, ESCRITORIO)
  AS (
    SELECT 
      OFFICECODE, 
      CITY
	FROM 
      OFFICES)
SELECT 
  OBSERVACAO, 
  COUNT(OBSERVACAO) QUANTIDADE
FROM (
  SELECT 
     SUM(QUANTIDADE) TOTAL, 
     NOMEPRODUTO, 
     'PRODUTO' AS OBSERVACAO
  FROM CTE_PRODUTO
         INNER JOIN CTE_ITEMPEDIDO USING (CODIGOPRODUTO)
         INNER JOIN CTE_PEDIDO USING (NUMERONOTA)
  WHERE 
     YEAR(DATAPEDIDO) = 2004
  GROUP BY
     NOMEPRODUTO
  HAVING 
     TOTAL BETWEEN 400 AND 800
 
  UNION
     
  SELECT 
	SUM(VALOR) TOTAL, 
    NOMECLIENTE, 
    'CLIENTE' AS OBSERVACAO
  FROM 
    CTE_CLIENTE 
       INNER JOIN CTE_PAGAMENTO USING (CODIGOCLIENTE)
       INNER JOIN CTE_VENDEDOR USING (CODIGOVENDEDOR)
       INNER JOIN CTE_ESCRITORIO USING (CODIGOESCRITORIO)
  WHERE 
      MONTH(DATAPAGAMENTO) IN (10,11,12)
  AND YEAR(DATAPAGAMENTO) = 2004
  AND ESCRITORIO IN ('LONDON', 'SAN FRANCISCO')
  GROUP BY
    NOMECLIENTE
  HAVING 
    TOTAL > 50000

  UNION 
  
  SELECT
    SUM(VALOR) TOTAL, 
    NOMEVENDEDOR, 
    'VENDEDOR' AS OBSERVACAO
  FROM 
    CTE_PAGAMENTO 
       INNER JOIN CTE_CLIENTE USING (CODIGOCLIENTE)
       INNER JOIN CTE_VENDEDOR USING (CODIGOVENDEDOR)
  WHERE 
    YEAR(DATAPAGAMENTO) = 2005
  GROUP BY 
    NOMEVENDEDOR
  HAVING 
   TOTAL > 200000) AS RESULTADO 
 GROUP BY OBSERVACAO;